# -*- Mode: makefile -*-
# RISC-V specific tweaks

VPATH += $(SRC_PATH)/tests/tcg/riscv64
TESTS += test-div
TESTS += noexec

# Disable compressed instructions for test-noc
TESTS += test-noc
test-noc: LDFLAGS = -nostdlib -static
run-test-noc: QEMU_OPTS += -cpu rv64,c=false

TESTS += test-aes
run-test-aes: QEMU_OPTS += -cpu rv64,zk=on

# Test for fcvtmod
TESTS += test-fcvtmod
test-fcvtmod: CFLAGS += -march=rv64imafdc
test-fcvtmod: LDFLAGS += -static
run-test-fcvtmod: QEMU_OPTS += -cpu rv64,d=true,zfa=true

TESTS += test-rvv-vmv-s-x-tail
test-rvv-vmv-s-x-tail: CFLAGS += -march=rv64gcv -mabi=lp64d
run-test-rvv-vmv-s-x-tail: QEMU_OPTS += -cpu rv64,v=true,vlen=128,elen=64,rvv_ta_all_1s=true,rvv_ma_all_1s=true
